### PR TITLE
Timeout middleware

### PR DESCRIPTION
**Pull request by wangdayong228**
This change is [Reviewable](https://reviewable.io/reviews/openweb3/go-rpc-provider/3)

### CODE REVIEW

**Review by boqiu — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openweb3/go-rpc-provider/3)* status: all files reviewed, 5 unresolved discussions (waiting on @Pana, @wangdayong228, and @wanliqun)

___
*[`provider_wrapper/provider.go` line 19 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/3#-N2ea1dn0_Oi3rEp0xIW:-N2ea1dn0_Oi3rEp0xIX:bjbqkgz) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/28bf66b9c08e51dd2467875f229fae8b55c42c1f/provider_wrapper/provider.go#L19)):*
> ```Go
> 	RequestTimeout time.Duration `default:"3s"`
> 	// Maximum number of connections may be established. The default value is 512.
> 	MaxConnectionNum int
> ```

How about to reuse the underly name `MaxConnsPerHost`?



_Code quote:_
```Go
MaxConnectionNum
```
___
*[`provider_wrapper/provider.go` line 32 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/3#-N2e_muB7rE2wsi13CVB:-N2e_muB7rE2wsi13CVC:b-dunvka) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/28bf66b9c08e51dd2467875f229fae8b55c42c1f/provider_wrapper/provider.go#L32)):*
> ```Go
> 	return o
> }
> ```

`WithMaxConnectionNum` missed?

What's more, builder pattern is not required. Generally, user could set fields in Option by himself.
___
*[`provider_wrapper/provider.go` line 33 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/3#-N2eaOlI4jOX36tw2T6V:-N2eaOlI4jOX36tw2T6W:b-llfrg2) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/28bf66b9c08e51dd2467875f229fae8b55c42c1f/provider_wrapper/provider.go#L33)):*
> ```Go
> }
> 
> func NewProviderWithOption(rawurl string, option *Option) (*MiddlewarableProvider, error) {
> ```

From your method name, stronlgy recommend to use value type to avoid unnecessary check for null pointer.



_Code quote:_
```Go
*Option
```
___
*[`provider_wrapper/provider.go` line 55 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/3#-N2ebTGNDaWxqEA4GO1Q:-N2ebTGNDaWxqEA4GO1R:bycz6fj) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/28bf66b9c08e51dd2467875f229fae8b55c42c1f/provider_wrapper/provider.go#L55)):*
> ```Go
> // wrapProvider wrap provider accroding to option
> func wrapProvider(p *MiddlewarableProvider, option *Option) *MiddlewarableProvider {
> 	if option == nil {
> ```

Already checked in `NewProviderWithOption`.



_Code quote:_
```Go
if option == nil
```
___
*[`provider_wrapper/provider_timeout.go` line 64 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/3#-N2edPGs0Ak5WC5PBgqs:-N2edPGs0Ak5WC5PBgqt:bq1rjcb) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/28bf66b9c08e51dd2467875f229fae8b55c42c1f/provider_wrapper/provider_timeout.go#L64)):*
> ```Go
> 
> func (t *TimeoutMiddleware) setContext(ctx context.Context) (context.Context, context.CancelFunc) {
> 	_, ok := ctx.Deadline()
> ```

Why ignore when the parent `ctx` is deadline context?

E.g. a business API requires completed in 10 secs, and only allow to access fullnode in 3 secs.



_Code quote:_
```Go
_, ok := ctx.Deadline()
```

**Review by wangdayong228 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openweb3/go-rpc-provider/3)* status: 4 of 10 files reviewed, 5 unresolved discussions (waiting on @boqiu, @Pana, and @wanliqun)

___
*[`provider_wrapper/provider.go` line 19 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/3#-N2ea1dn0_Oi3rEp0xIW:-N2k5egu7xoJDDyozZoY:b-896fix) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/28bf66b9c08e51dd2467875f229fae8b55c42c1f/provider_wrapper/provider.go#L19)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

How about to reuse the underly name `MaxConnsPerHost`?
</blockquote></details>

Done.
___
*[`provider_wrapper/provider.go` line 32 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/3#-N2e_muB7rE2wsi13CVB:-N2k5fmPCcDeGIGwQM8W:b-896fix) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/28bf66b9c08e51dd2467875f229fae8b55c42c1f/provider_wrapper/provider.go#L32)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

`WithMaxConnectionNum` missed?

What's more, builder pattern is not required. Generally, user could set fields in Option by himself.
</blockquote></details>

Done.
___
*[`provider_wrapper/provider.go` line 33 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/3#-N2eaOlI4jOX36tw2T6V:-N2kC-pu3QJT0KeWdL3M:b-896fix) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/28bf66b9c08e51dd2467875f229fae8b55c42c1f/provider_wrapper/provider.go#L33)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

From your method name, stronlgy recommend to use value type to avoid unnecessary check for null pointer.
</blockquote></details>

Done.
___
*[`provider_wrapper/provider.go` line 55 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/3#-N2ebTGNDaWxqEA4GO1Q:-N2kC0SD303d2BrAYtTq:b-896fix) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/28bf66b9c08e51dd2467875f229fae8b55c42c1f/provider_wrapper/provider.go#L55)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Already checked in `NewProviderWithOption`.
</blockquote></details>

Done.
___
*[`provider_wrapper/provider_timeout.go` line 64 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/3#-N2edPGs0Ak5WC5PBgqs:-N2kDY9t-1-tfKUgTk4A:bzab99a) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/28bf66b9c08e51dd2467875f229fae8b55c42c1f/provider_wrapper/provider_timeout.go#L64)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Why ignore when the parent `ctx` is deadline context?

E.g. a business API requires completed in 10 secs, and only allow to access fullnode in 3 secs.
</blockquote></details>

ignore if have set deadline for avoiding overwrite user's set

**Review by boqiu — COMMENTED** [review]
> Reviewed 5 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openweb3/go-rpc-provider/3)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @boqiu, @Pana, @wangdayong228, and @wanliqun)

___
*[`provider_wrapper/provider.go` line 33 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/3#-N2eaOlI4jOX36tw2T6V:-N2kdiIBBajLZh6W2zj_:burkoet) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/28bf66b9c08e51dd2467875f229fae8b55c42c1f/provider_wrapper/provider.go#L33)):*
<details><summary><i>Previously, wangdayong228 (dyoung) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not changed yet?
___
*[`provider_wrapper/provider_timeout.go` line 64 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/3#-N2edPGs0Ak5WC5PBgqs:-N2kehqKDPU9JObZo3SZ:bjst2wa) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/28bf66b9c08e51dd2467875f229fae8b55c42c1f/provider_wrapper/provider_timeout.go#L64)):*
<details><summary><i>Previously, wangdayong228 (dyoung) wrote…</i></summary><blockquote>

ignore if have set deadline for avoiding overwrite user's set
</blockquote></details>

As I mentioned, `ctx` from user is not only for RPC request, but for the entire business process. Otherwise, the timeout of RPC is not the same with `RequestTimeout`.

**Review by boqiu — COMMENTED** [review]
> Reviewed 1 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openweb3/go-rpc-provider/3)* status: all files reviewed, 1 unresolved discussion (waiting on @Pana, @wangdayong228, and @wanliqun)

**Review by boqiu — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openweb3/go-rpc-provider/3#-:-N2kq35b7HonX0vupA7d:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Pana and @wanliqun)

**Review by wangdayong228 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openweb3/go-rpc-provider/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Pana and @wanliqun)

___
*[`provider_wrapper/provider.go` line 33 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/3#-N2eaOlI4jOX36tw2T6V:-N2kq0Jp4RDikgMm-qXU:b-896fix) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/28bf66b9c08e51dd2467875f229fae8b55c42c1f/provider_wrapper/provider.go#L33)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Not changed yet?
</blockquote></details>

Done.

**Review by boqiu — APPROVED** [review]

**Pull request merged**
