### PR TITLE
set ws ping interval

### PR DESCRIPTION
**Pull request by wangdayong228**
This change is [Reviewable](https://reviewable.io/reviews/openweb3/go-rpc-provider/10)

### CODE REVIEW

**Review by wanliqun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openweb3/go-rpc-provider/10)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @wangdayong228 and @wanliqun)

___
*[`websocket.go` line 222 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/10#-NBFcLWi58HOHdMjhFJr:-NBFcLWi58HOHdMjhFJs:b-ih6m1r) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/2f1b3876129ed8fcb13b80744f1d63bfed367e51/websocket.go#L222)):*
> ```Go
> }
> 
> func (wc *websocketCodec) peerInfo() PeerInfo {
> ```

This method is not exported and used anywhere, seems it's not needed at all.
___
*[`websocket.go` line 265 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/10#-NBFcnEM5ngxmrHmL8QN:-NBFcnEM5ngxmrHmL8QO:b77f2d6) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/2f1b3876129ed8fcb13b80744f1d63bfed367e51/websocket.go#L265)):*
> ```Go
> 
> func get1stWsOption(option []WebsocketOption) WebsocketOption {
> 	_option := WebsocketOption{}
> ```

use default ping interval?
_option := WebsocketOption{ WsPingInterval: wsPingInterval }

**Review by wanliqun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openweb3/go-rpc-provider/10)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @wangdayong228 and @wanliqun)

___
*[`server.go` line 157 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/10#-NBFdA79053TwGIxG_gO:-NBFdA79053TwGIxG_gP:btpcdyc) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/2f1b3876129ed8fcb13b80744f1d63bfed367e51/server.go#L157)):*
> ```Go
> // PeerInfoFromContext to get information about the client connection related to
> // the current method call.
> type PeerInfo struct {
> ```

Can we just reuse the PeerInfo struct from geth?

**Review by wanliqun — COMMENTED** [review]
Some trivial fixes if possible

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openweb3/go-rpc-provider/10#-:-NBFdxun3DndosIqMl9_:b-3kiynb)* status: all files reviewed, 3 unresolved discussions (waiting on @wangdayong228)

**Review by wangdayong228 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openweb3/go-rpc-provider/10)* status: all files reviewed, 3 unresolved discussions (waiting on @wanliqun)

___
*[`server.go` line 157 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/10#-NBFdA79053TwGIxG_gO:-NBGVbGP-rgM2_v9T88w:b8elc3n) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/2f1b3876129ed8fcb13b80744f1d63bfed367e51/server.go#L157)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

Can we just reuse the PeerInfo struct from geth?
</blockquote></details>

This it the struct of geth, because go-rpc-provider is a old version of geth that have no this struct.
___
*[`websocket.go` line 222 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/10#-NBFcLWi58HOHdMjhFJr:-NBGVr-B6jqmLrzpWDoD:b-q5nr0l) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/2f1b3876129ed8fcb13b80744f1d63bfed367e51/websocket.go#L222)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

This method is not exported and used anywhere, seems it's not needed at all.
</blockquote></details>

It's copied from geth at new version
___
*[`websocket.go` line 265 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/10#-NBFcnEM5ngxmrHmL8QN:-NBGWu38DPrI-M4iNeXr:b-896fix) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/2f1b3876129ed8fcb13b80744f1d63bfed367e51/websocket.go#L265)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

use default ping interval?
_option := WebsocketOption{ WsPingInterval: wsPingInterval }
</blockquote></details>

Done.

**Review by wanliqun — APPROVED** [review]

**Pull request merged**
