### PR TITLE
Circuit breaker

### PR DESCRIPTION
**Pull request by wangdayong228**
This change is [Reviewable](https://reviewable.io/reviews/openweb3/go-rpc-provider/17)

### CODE REVIEW

**Review by wanliqun — CHANGES_REQUESTED** [review]
I would recomment to refer to `https://github.com/sony/gobreaker`  or `https://github.com/mercari/go-circuitbreaker` or any possibilities to import them?

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openweb3/go-rpc-provider/17#-:-Nopi0hbEAytYuc0q7Td:bog9byl)* status: 0 of 5 files reviewed, 7 unresolved discussions (waiting on @boqiu and @wangdayong228)

___
*[`provider_wrapper/circuit_breaker.go` line 21 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/17#-NopVPb43nVX63AqZxwj:-NopVPb43nVX63AqZxwk:b-8ngp33) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/e2a796c97f1b1cc0b5168637eb65be99a21e756e/provider_wrapper/circuit_breaker.go#L21)):*
> ```Go
> 	BREAKER_CLOSED BreakerState = iota
> 	BREAKER_HALF_OPEN
> 	BREAKER_OPEN
> ```

Shouting case seems to be an unusual naming convention in golang.



_Code quote:_
```Go
	BREAKER_CLOSED BreakerState = iota
	BREAKER_HALF_OPEN
	BREAKER_OPEN
```
___
*[`provider_wrapper/circuit_breaker.go` line 27 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/17#-NopSw50As9BDc34N45j:-NopSw50As9BDc34N45k:b-e9nq3i) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/e2a796c97f1b1cc0b5168637eb65be99a21e756e/provider_wrapper/circuit_breaker.go#L27)):*
> ```Go
> var ErrUnknownCircuitState = errors.New("unknown circuit state")
> 
> type DefaultCircuitBreaderOption struct {
> ```

typo `DefaultCircuitBreakerOptions`?
___
*[`provider_wrapper/circuit_breaker.go` line 41 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/17#-NopU_iyAZcqjAEUJJ4x:-NopU_iz-cZJEmUiLz7_:b-xu7ww2) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/e2a796c97f1b1cc0b5168637eb65be99a21e756e/provider_wrapper/circuit_breaker.go#L41)):*
> ```Go
> func NewDefaultCircuitBreaker(option ...DefaultCircuitBreaderOption) *DefaultCircuitBreaker {
> 	if len(option) == 0 {
> 		option = []DefaultCircuitBreaderOption{}
> ```

Option is still an empty array, the later use of`option[0]` may cause panic.
___
*[`provider_wrapper/circuit_breaker.go` line 51 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/17#-NopWHQw0DkOMivitTeq:-NopWHQxB2YKI5oGO5-4:b-b5pp6o) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/e2a796c97f1b1cc0b5168637eb65be99a21e756e/provider_wrapper/circuit_breaker.go#L51)):*
> ```Go
> 
> func (c *DefaultCircuitBreaker) Do(handler func() error) error {
> 	switch c.State() {
> ```

Consider concurrency support? Otherwise, we might have a race condition problem.
___
*[`provider_wrapper/circuit_breaker.go` line 68 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/17#-NopfqYn-z_k58PqvMDC:-NopfqYn-z_k58PqvMDD:b-amvsl4) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/e2a796c97f1b1cc0b5168637eb65be99a21e756e/provider_wrapper/circuit_breaker.go#L68)):*
> ```Go
> 			c.lastState = BREAKER_OPEN
> 		} else {
> 			c.lastState = BREAKER_HALF_OPEN
> ```

It's not possible to come from Closed status to Half_open status.
___
*[`provider_wrapper/circuit_breaker.go` line 108 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/17#-Nopg8FgCiBqS3ixixLv:-Nopg8FgCiBqS3ixixLw:b-7thqzb) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/e2a796c97f1b1cc0b5168637eb65be99a21e756e/provider_wrapper/circuit_breaker.go#L108)):*
> ```Go
> 	}
> 
> 	return true, time.Since(c.failHistory[failLen-c.MaxFail]) - c.sinceLastFail()
> ```

This doesn't seem to work. If we need to calculate how many failures within a time range, we might need to use a sliding window.
___
*[`provider_wrapper/circuit_breaker.go` line 112 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/17#-NopcvqVD1QGa69b9LQH:-NopcvqVD1QGa69b9LQI:b-mnm7jj) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/e2a796c97f1b1cc0b5168637eb65be99a21e756e/provider_wrapper/circuit_breaker.go#L112)):*
> ```Go
> 
> func (c *DefaultCircuitBreaker) sinceLastFail() time.Duration {
> 	lastFail := c.failHistory[len(c.failHistory)-1]
> ```

recommend to check the length of array as a defense guard

**Review by wangdayong228 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openweb3/go-rpc-provider/17)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @boqiu and @wanliqun)

___
*[`provider_wrapper/circuit_breaker.go` line 21 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/17#-NopVPb43nVX63AqZxwj:-NotHTLQ5U80wtEt-gX-:b-vpu1rx) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/e2a796c97f1b1cc0b5168637eb65be99a21e756e/provider_wrapper/circuit_breaker.go#L21)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

Shouting case seems to be an unusual naming convention in golang.
</blockquote></details>

Camel case naming is not easy to distinguish whether it is an enumeration, but this way is easier to distinguish. Do you have any idea?
___
*[`provider_wrapper/circuit_breaker.go` line 41 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/17#-NopU_iyAZcqjAEUJJ4x:-NotHIMyCKGrrIr9uQBf:b-896fix) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/e2a796c97f1b1cc0b5168637eb65be99a21e756e/provider_wrapper/circuit_breaker.go#L41)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

Option is still an empty array, the later use of`option[0]` may cause panic.
</blockquote></details>

Done.
___
*[`provider_wrapper/circuit_breaker.go` line 51 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/17#-NopWHQw0DkOMivitTeq:-NotHJnd5WZBaYhFb6Dt:b-896fix) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/e2a796c97f1b1cc0b5168637eb65be99a21e756e/provider_wrapper/circuit_breaker.go#L51)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

Consider concurrency support? Otherwise, we might have a race condition problem.
</blockquote></details>

Done.
___
*[`provider_wrapper/circuit_breaker.go` line 68 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/17#-NopfqYn-z_k58PqvMDC:-NotHL4w761fmc096Wxe:b-896fix) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/e2a796c97f1b1cc0b5168637eb65be99a21e756e/provider_wrapper/circuit_breaker.go#L68)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

It's not possible to come from Closed status to Half_open status.
</blockquote></details>

Done.
___
*[`provider_wrapper/circuit_breaker.go` line 108 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/17#-Nopg8FgCiBqS3ixixLv:-NotHP6W17pkyWXVRjj6:b-896fix) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/e2a796c97f1b1cc0b5168637eb65be99a21e756e/provider_wrapper/circuit_breaker.go#L108)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

This doesn't seem to work. If we need to calculate how many failures within a time range, we might need to use a sliding window.
</blockquote></details>

Done.
___
*[`provider_wrapper/circuit_breaker.go` line 112 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/17#-NopcvqVD1QGa69b9LQH:-NotHQDL8gzjn_U7Sofy:b-896fix) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/e2a796c97f1b1cc0b5168637eb65be99a21e756e/provider_wrapper/circuit_breaker.go#L112)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

recommend to check the length of array as a defense guard
</blockquote></details>

Done.

**Review by wangdayong228 — COMMENTED** [review]
The go-rpc-provider supports a default circuit breaker, if users are familiar with any library, they can create a new CircuitBraker to use them.

> *[Reviewable](https://reviewable.io/reviews/openweb3/go-rpc-provider/17#-:-NotI8Kr9r-U8TdgMp5D:b-iqvhl3)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @boqiu and @wanliqun)

**Review by wanliqun — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openweb3/go-rpc-provider/17)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @boqiu and @wangdayong228)

___
*[`provider_wrapper/circuit_breaker.go` line 69 at r2](https://reviewable.io/reviews/openweb3/go-rpc-provider/17#-NouCxNM624Y-sZ9Qtmn:-NouCxNM624Y-sZ9Qtmo:b-8o2zhl) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/5830c67bc4e95571b6c603fb628843f8a598b85f/provider_wrapper/circuit_breaker.go#L69)):*
> ```Go
> 			if !isReached || maxfailUsedTime > c.FailTimeWindow {
> 				return err
> 			}
> ```

can we just create a function like `maxFailAchieved` ignoring  details like`isReached, maxfailUsedTime`? 



_Code quote:_
```Go
			isReached, maxfailUsedTime := c.maxfailUsedTime()

			if !isReached || maxfailUsedTime > c.FailTimeWindow {
				return err
			}
```
___
*[`provider_wrapper/circuit_breaker.go` line 100 at r2](https://reviewable.io/reviews/openweb3/go-rpc-provider/17#-NouBTmvBj6ccIdQD6cV:-NouBTmw71F5U7e4jKO2:by6t4y8) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/5830c67bc4e95571b6c603fb628843f8a598b85f/provider_wrapper/circuit_breaker.go#L100)):*
> ```Go
> 
> func (c *DefaultCircuitBreaker) State() BreakerState {
> 	if c.lastState == BREAKER_OPEN && c.sinceLastFail() > c.OpenColdTime {
> ```

we also need to add mutex lock here.

**Review by wangdayong228 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openweb3/go-rpc-provider/17)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @boqiu and @wanliqun)

___
*[`provider_wrapper/circuit_breaker.go` line 69 at r2](https://reviewable.io/reviews/openweb3/go-rpc-provider/17#-NouCxNM624Y-sZ9Qtmn:-NoupQ5iAL_XfI7MIr4C:b-896fix) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/5830c67bc4e95571b6c603fb628843f8a598b85f/provider_wrapper/circuit_breaker.go#L69)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

can we just create a function like `maxFailAchieved` ignoring  details like`isReached, maxfailUsedTime`?
</blockquote></details>

Done.
___
*[`provider_wrapper/circuit_breaker.go` line 100 at r2](https://reviewable.io/reviews/openweb3/go-rpc-provider/17#-NouBTmvBj6ccIdQD6cV:-NoupRjQCbAxdvHZul9l:b-896fix) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/5830c67bc4e95571b6c603fb628843f8a598b85f/provider_wrapper/circuit_breaker.go#L100)):*
<details><summary><i>Previously, wanliqun (wanliqun) wrote…</i></summary><blockquote>

we also need to add mutex lock here.
</blockquote></details>

Done.

**Review by wanliqun — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/openweb3/go-rpc-provider/17#-:-Nov3EmH1gzt74DLgtKM:bnfp4nl)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @boqiu)

**Pull request merged**
