### PR TITLE
add provider wrapper

### PR DESCRIPTION
**Pull request by wangdayong228**
This change is [Reviewable](https://reviewable.io/reviews/openweb3/go-rpc-provider/2)

### CODE REVIEW

**Review by boqiu — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openweb3/go-rpc-provider/2)* status: all files reviewed, 4 unresolved discussions (waiting on @Pana, @wangdayong228, and @wanliqun)

___
*[`provider_wrapper/provider_base.go` line 19 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/2#-N2KGWwn1p9i5HjB-FcC:-N2KGWwn1p9i5HjB-FcD:bqweuky) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/7edce67f5bb153ee4dd58a761f2c06daa6bf454a/provider_wrapper/provider_base.go#L19)):*
> ```Go
> 		if u, err := url.Parse(nodeUrl); err == nil {
> 			if u.Scheme == "http" || u.Scheme == "https" {
> 				fasthttpClient := new(fasthttp.Client)
> ```

So, if `maxConnectionNum` not specified, `fasthttpclient` will not be used?
___
*[`provider_wrapper/provider_middleware.go` line 29 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/2#-N2KH6q3EYx9Yh6J4dwB:-N2KH6q3EYx9Yh6J4dwC:b-fflz0m) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/7edce67f5bb153ee4dd58a761f2c06daa6bf454a/provider_wrapper/provider_middleware.go#L29)):*
> ```Go
> 
> type CallFunc func(resultPtr interface{}, method string, args ...interface{}) error
> type CallContextFunc func(ctx context.Context, result interface{}, method string, args ...interface{}) error
> ```

How about to allow middleware to change the `ctx`?
___
*[`provider_wrapper/provider_retry.go` line 13 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/2#-N2KHgO65S857a-pdMpP:-N2KHgO65S857a-pdMpQ:b-6updgg) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/7edce67f5bb153ee4dd58a761f2c06daa6bf454a/provider_wrapper/provider_retry.go#L13)):*
> ```Go
> )
> 
> type RetriableProvider struct {
> ```

Another way is to define a `Retry` middleware, just like `OutputToConsoleMiddleware`.
___
*[`provider_wrapper/provider_retry.go` line 79 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/2#-N2KIHziD3z2YjmvM4ga:-N2KIHziD3z2YjmvM4gb:bj9uw29) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/7edce67f5bb153ee4dd58a761f2c06daa6bf454a/provider_wrapper/provider_retry.go#L79)):*
> ```Go
> 		}
> 
> 		remain--
> ```

move to the end?

E.g. maxRetry == 1, no retry occurred.

**Review by wangdayong228 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openweb3/go-rpc-provider/2)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @boqiu, @Pana, and @wanliqun)

___
*[`provider_wrapper/provider_base.go` line 19 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/2#-N2KGWwn1p9i5HjB-FcC:-N2KL9KHCK6GIaAESU4_:bkck50i) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/7edce67f5bb153ee4dd58a761f2c06daa6bf454a/provider_wrapper/provider_base.go#L19)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

So, if `maxConnectionNum` not specified, `fasthttpclient` will not be used?
</blockquote></details>

If not specify maxConnectionNum, it will use default fasthttpclient
___
*[`provider_wrapper/provider_middleware.go` line 29 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/2#-N2KH6q3EYx9Yh6J4dwB:-N2KLGSdCnajuJBwtQP7:bg9fi3a) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/7edce67f5bb153ee4dd58a761f2c06daa6bf454a/provider_wrapper/provider_middleware.go#L29)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

How about to allow middleware to change the `ctx`?
</blockquote></details>

It could be change context in CallContextFunc/BatchCallContextFunc middleware when HookCallContext/HookBatchCallContext
___
*[`provider_wrapper/provider_retry.go` line 13 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/2#-N2KHgO65S857a-pdMpP:-N2KLpfVB5Pm6cv_w6DP:b-cvzu0o) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/7edce67f5bb153ee4dd58a761f2c06daa6bf454a/provider_wrapper/provider_retry.go#L13)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Another way is to define a `Retry` middleware, just like `OutputToConsoleMiddleware`.
</blockquote></details>

It may need one more step to create four functions with the same retry related options to create functions for creating retry middleware, more complex than the current for user
___
*[`provider_wrapper/provider_retry.go` line 79 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/2#-N2KIHziD3z2YjmvM4ga:-N2KNyQX03YzDYWFXzMw:b-896fix) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/7edce67f5bb153ee4dd58a761f2c06daa6bf454a/provider_wrapper/provider_retry.go#L79)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

move to the end?

E.g. maxRetry == 1, no retry occurred.
</blockquote></details>

Done.

**Review by boqiu — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openweb3/go-rpc-provider/2)* status: all files reviewed, 1 unresolved discussion (waiting on @Pana, @wangdayong228, and @wanliqun)

___
*[`provider_wrapper/provider_middleware.go` line 29 at r1](https://reviewable.io/reviews/openweb3/go-rpc-provider/2#-N2KH6q3EYx9Yh6J4dwB:-N2KRp9i0tB0imwzmGua:bgcece3) ([raw file](https://github.com/openweb3/go-rpc-provider/blob/7edce67f5bb153ee4dd58a761f2c06daa6bf454a/provider_wrapper/provider_middleware.go#L29)):*
<details><summary><i>Previously, wangdayong228 (dyoung) wrote…</i></summary><blockquote>

It could be change context in CallContextFunc/BatchCallContextFunc middleware when HookCallContext/HookBatchCallContext
</blockquote></details>

How to change `ctx` in CallContextFunc? In my mind, method should return a new context to change context.

**Review by boqiu — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openweb3/go-rpc-provider/2#-:-N2LAKNy8GG8AnX6rFOK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Pana and @wanliqun)

**Review by boqiu — APPROVED** [review]

**Pull request merged**
